# Server
server.port=8080

# Database - UPDATE THIS WITH YOUR ACTUAL PASSWORD
spring.datasource.url=jdbc:mysql://localhost:3306/auxera
spring.datasource.username=root
spring.datasource.password=azeez
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# CORS
cors.allowed-origins=http://localhost:5173

# Brevo (Sendinblue) Email Configuration
brevo.api.key=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
brevo.api.url=https://api.brevo.com/v3
# User email configuration
user.mail=azeez3646@gmail.com
brevo.sender.name=AUXERA
